[package]
name = "rmod"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "macros"] }
tokio = { version = "1", features = ["full"] }
once_cell = "1"
axum = "0.8.8"
tower = "0.5.3"
tower-http = "0.6.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
